[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
mumbai = "${POLYGON_MUMBAI_RPC_URL}"
arbitrum-goerli = "${ARBITRUM_RPC_URL}"

[etherscan]
polygon = { key = "${POLYGON_ETHERSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }
avalanche = { key = "${AVALANCHE_ETHERSCAN_API_KEY}", url = "https://api.snowtrace.io/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mumbai = { key = "${MUMBAI_ETHERSCAN_API_KEY}", url = "https://api-testnet.polygonscan.com/api" }
arbitrum-goerli = { key = "${ARBITRUM_ETHERSCAN_API_KEY}", url = "https://api-goerli.arbiscan.io/api" }

[doc]
title = 'MetaHuman Governor Contracts'
ignore = ['src/hm-token/*.sol','src/vhm-token/*.sol','contracts/*.sol']
