[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mumbai = "${POLYGON_MUMBAI_RPC_URL}"
arbitrum-goerli = "${ARBITRUM_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mumbai = { key = "${MUMBAI_ETHERSCAN_API_KEY}", url = "https://api-testnet.polygonscan.com/api" }
arbitrum-goerli = { key = "${ARBITRUM_ETHERSCAN_API_KEY}", url = "https://api-goerli.arbiscan.io/api" }

[doc]
title = 'MetaHuman Governor Contracts'
ignore = ['src/hm-token/*.sol','src/vhm-token/*.sol','contracts/*.sol']
