apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ env['HUMAN_RELAYER_SERVICE'] }}
  annotations:
    run.googleapis.com/launch-stage: BETA

spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/container-dependencies: '{"relayer-app":["guardian"]}'

    spec:
      containers:
      - image: "{{ env['GCP_REGION'] }}-docker.pkg.dev/{{ env['GCP_PROJECT_ID'] }}/blockydevs/guardiand:latest"
        name: guardian
        args:
        - spy
        - --nodeKey
        - /node.key
        - --spyRPC
        - '[::]:7073'
        - --network
        - {{ env['GUARDIAN_NETWORK'] }}
        - --bootstrap
        - {{ env['GUARDIAN_BOOTSTRAP'] }}
        env:
        - name: REDIS_HOST
          value: "{{ env['REDIS_HOST'] }}"
        - name: REDIS_PORT
          value: "{{ env['REDIS_PORT'] }}"
        - name: REDIS_CURRENT_LOCATION_ID
          value: "{{ env['REDIS_CURRENT_LOCATION_ID'] }}"

      - image: "{{ env['GCP_REGION'] }}-docker.pkg.dev/{{ env['GCP_PROJECT_ID'] }}/blockydevs/relayer-app:latest"
        name: relayer-app
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "{{ env['ENVIRONMENT'] }}"
        - name: REDIS_HOST
          value: "{{ env['REDIS_HOST'] }}"
        - name: REDIS_PORT
          value: "{{ env['REDIS_PORT'] }}"
        - name: REDIS_CURRENT_LOCATION_ID
          value: "{{ env['REDIS_CURRENT_LOCATION_ID'] }}"
        - name: PROVIDERS_CHAIN_10002
          value: "{{ env['PROVIDERS_CHAIN_10002'] }}"
        - name: HUB_RELAY_CHAIN_ID
          value: "{{ env['HUB_RELAY_CHAIN_ID'] }}"
        - name: HUB_RELAY_CHAIN_ADDRESS
          value: "{{ env['HUB_RELAY_CHAIN_ADDRESS'] }}"
        - name: SPOKE_RELAY_CHAIN_5
          value: "{{ env['SPOKE_RELAY_CHAIN_5'] }}"
        - name: PROVIDERS_CHAIN_10002
          value: "{{ env['PROVIDERS_CHAIN_10002'] }}"
        - name: PRIVATE_KEYS_CHAIN_10002
          value: "{{ env['PRIVATE_KEYS_CHAIN_10002'] }}"
        - name: PRIVATE_KEYS_CHAIN_5
          value: "{{ env['PRIVATE_KEYS_CHAIN_5'] }}"
        - name: PROVIDERS_CHAIN_5
          value: "{{ env['PROVIDERS_CHAIN_5'] }}"
          
