apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blockydevs
  namespace: "{{ env['GCP_PROJECT_ID'] }}"
spec:
  template:
    spec:
      containers:      
      - image: "{{ env['GCP_REGION'] }}-docker.pkg.dev/{{ env['GCP_PROJECT_ID'] }}/blockydevs/guardiand:latest"
        name: guardian
        args:
        - ./guardiand spy --nodeKey /node.key --spyRPC '[::]:7073' --network {{ env['GUARDIAN_NETWORK'] }} --bootstrap {{ env['GUARDIAN_BOOTSTRAP'] }}
        ports:
        - containerPort: 7073
        env:
        - name: REDIS_HOST
          value: "{{ env['REDIS_HOST'] }}"
        - name: REDIS_PORT
          value: "{{ env['REDIS_PORT'] }}"
        - name: REDIS_CURRENT_LOCATION_ID
          value: "{{ env['REDIS_CURRENT_LOCATION_ID'] }}"
