version: '3.8'
services:
  redis-docker:
    image: redis
    ports:
      - 6379:6379


  spy-docker:
    image: ghcr.io/wormhole-foundation/guardiand:latest
    entrypoint: /guardiand spy --nodeKey /node.key --spyRPC "[::]:7073" --network /wormhole/mainnet/2 --bootstrap /dns4/wormhole-mainnet-v2-bootstrap.certus.one/udp/8999/quic/p2p/12D3KooWQp644DK27fd3d4Km3jr7gHiuJJ5ZGmy8hH4py7fP4FP7
    ports:
      - 7073:7073
    platform: linux/amd64

  human-relayer-app:
    build:
      context: .
      dockerfile: Dockerfile.human-relayer-app
    ports:
      - 8080:8080
    depends_on:
      - spy-docker
      - redis-docker
    env_file:
      - human-relayer-app/.env
