name: Smartcontracts

on: 
  workflow_dispatch:
  # Inputs the workflow accepts.
    inputs:
      SPOKE_PARAMS:
        description: 'Json with parameters for spoke deploy'
        required: true
        type: string
      HM_TOKEN_ADDRESS:
        # description: 'HM Token Address'
        required: true
        type: string
      TIMELOCK:
        description: "Transfer governance ownership to timelock"
        required: true
        type: boolean
        default: false

defaults:
  run:
    working-directory: smartcontracts

env:
  FOUNDRY_PROFILE: ci
  # user data
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  SECOND_PRIVATE_KEY: ${{ secrets.SECOND_PRIVATE_KEY }}
  THIRD_PRIVATE_KEY: ${{ secrets.THIRD_PRIVATE_KEY }}
  HUB_RPC_URL: ${{ vars.HUB_RPC_URL }}
  # HUB_VOTE_TOKEN_ADDRESS: ${{ vars.HUB_VOTE_TOKEN_ADDRESS }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  MAGISTRATE_ADDRESS: ${{ secrets.MAGISTRATE_ADDRESS }}
  # hub 
  HUB_CORE_BRIDGE_ADDRESS: ${{ vars.HUB_CORE_BRIDGE_ADDRESS }}
  HUB_CHAIN_ID: ${{ vars.HUB_CHAIN_ID }}
  VOTE_TOKEN_ADDRESS: ${{ vars.VOTE_TOKEN_ADDRESS }}
  HUB_HM_TOKEN_ADDRESS: ${{ vars.HUB_HM_TOKEN_ADDRESS }}
  # spoke deployment
  # SPOKE_VOTE_TOKEN_ADDRESS: ${{ vars.SPOKE_VOTE_TOKEN_ADDRESS }}
  # from inputs
  # HM_TOKEN_ADDRESS: ${{ inputs.HM_TOKEN_ADDRESS }}
  ADDRESS_TO_FUND: ${{ inputs.ADDRESS_TO_FUND }}
  TIMELOCK: ${{ inputs.TIMELOCK }}
  DESCRIPTION: ${{ inputs.DESCRIPTION }}
  SPOKE_PARAMS: ${{ inputs.SPOKE_PARAMS }}


jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Deploy contracts
        run: ./deploy.sh

      # store output jsons as artifact, for download see https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#download-an-artifact
      - uses: actions/upload-artifact@v3
        with:
          name: run-latest
          path: |
            broadcast/

